name: dostuff
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Test Stuff dostuff
    #environment: deploy
    steps:
      - name: Test dostuff step
        run: |
            echo "hello yall"
            exit 0
