name: my checks
on:
    pull_request:
        types: [opened, synchronize, reopened, auto_merge_enabled]
    merge_group:

jobs:
    test:
        runs-on: ubuntu-latest
        name: Test Stuff
        steps:
          - name: Test step
            run: |
                echo "hello world"
                exit 0
    call-dostuff:
        runs-on: ubuntu-latest
        name: dostuff Caller
#        if: github.event_name != 'pull_request'
        steps:
          - uses: actions/checkout@v4
          - name: hi
            uses: ./.github/workflows/dostuff.yaml
          - name: follow-up
            run: exit 0
    other-delegate:
        name: Nested
        uses: ./.github/workflows/nested.yaml
 
