name: my checks
on:
    pull_request:
        types: [opened, synchronize, reopened, auto_merge_enabled]
    merge_group:

jobs:
    test:
        runs-on: ubuntu-latest
        name: Test Stuff
        steps:
          - name: Test step
            run: |
                echo "hello world"
                exit 0
    deploy:
        runs-on: ubuntu-latest
        name: Execute Deploy
        #if: github.event_name != 'pull_request'
        environment: secretsenv
        steps:
          - name: Test dostuff step
            run: |
                echo "hello yall"
                exit 0
    other-delegate:
        name: Nested
        uses: ./.github/workflows/nested.yaml
 
